version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7.0
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-apply:
    description: "Initializes and applies terraform configuration"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Format code and initialise Terraform
          command: |
            cd infrastructure/<<parameters.stage>>
            terraform fmt
            terraform get -update=true
            terraform init
      - run:
          name: Apply infrastructure changes
          command: |
            cd infrastructure/<<parameters.stage>>
            terraform apply -auto-approve

jobs:
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  terraform-init-and-apply-to-production:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          stage: "production"

workflows:
  version: 2
  check-and-deploy-production:
    jobs:
      - assume-role-production:
          context: api-assume-role-production-context
      - terraform-init-and-apply-to-production:
          requires:
            - assume-role-production
