account_number_query = (
  "SELECT "
  "aws.mail_merge_reference AS mail_merge_reference, "
  "CONCAT(aws.lead_liable_name, ' ', aws.lead_liable_lastname) AS name, "
  "CONCAT(aws.for_addr1, ', ', aws.for_addr2, ', ', aws.for_addr3, ', ', aws.for_addr4, ', ', aws.for_postcode) AS forwarding_address, "
  "CONCAT(aws.addr1, ', ', aws.addr2, ', ', aws.addr3, ', ', aws.addr4, ', ', aws.postcode) AS property_address, "
  "aws.vo_band AS vo_band, "
  "coalesce(fdm.additional_names, fdm_exemptions.additional_names) AS additional_names, "
  "fdm.discount_1 AS discount_1, "
  "fdm.discount_2 AS discount_2, "
  "fdm.reduction AS reduction, "
  "aws.payment_method_code AS payment_method_code, "
  "fdm_exemptions.exemption_class AS exemption_class, "
  "exemption_reasons.reason AS exemption_reason, "
  "aws.property_ref as property_ref, "
  "ddd.\"20_21_gross_debit_12_instalments\" as \"20_21_gross_debit_12_instalments\", "
  "ROUND(aws.estimated_21_22_charge::numeric, 2) as estimated_21_22_charge_to_2dp, "
  "ROUND(aws.estimated_21_22_charge::numeric - (ROUND(aws.estimated_21_22_charge::numeric / 12) * 11), 2) as first_instalment, "
  "ROUND(aws.estimated_21_22_charge::numeric / 12) as other_instalments, "
  "COALESCE(apd.short_description, 'Bill will not be sent') "
  "FROM aws_academy_recovered_october AS aws "
  "LEFT JOIN fdm_mail_data_march AS fdm "
  "ON aws.mail_merge_reference = fdm.account_number "
  "LEFT JOIN fdm_mail_exemptions_march AS fdm_exemptions "
  "ON aws.mail_merge_reference = fdm_exemptions.account_number "
  "LEFT JOIN exemption_reasons "
  "ON exemption_reasons.class = fdm_exemptions.exemption_class "
  "LEFT JOIN direct_debit_discrepancies AS ddd "
  "ON ddd.mail_merge_reference = aws.mail_merge_reference "
  "LEFT JOIN account_profiles AS ap "
  "ON aws.id = ap.aws_academy_recovered_october_id "
  "LEFT JOIN account_profiles_description AS apd "
  "ON ap.account_profiles_description_id = apd.id "
  "WHERE aws.mail_merge_reference = "
)
